[lint]
select = ["E", "F", "B", "D", "I", "N", "UP", "ANN", "S", "BLE", "FBT", "COM", "C4", "DTZ", "T10", "ISC", "ICN", "G", "INP", "PIE", "T20", "PYI", "PT", "Q", "RSE", "RET", "SLF", "SIM", "TID", "ARG", "PTH", "ERA", "PD", "PGH", "PL", "TRY", "FLY", "PERF", "FURB", "LOG", "RUF"]
ignore = ["D100", "D104"]
exclude = [
    "**/migrations/*",
    "core/settings.py",
    "manage.py",
    "main.py",
    "core/asgi.py",
    "core/wsgi.py",
]

[lint.per-file-ignores]
"**/tests.py" = ["S101", "PLR2004"]
"**/test_*.py" = ["S101", "PLR2004"]

[lint.pydocstyle]
convention = "google"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
