# Generated by Django 6.0.3 on 2026-04-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publish_year', models.IntegerField(blank=True, null=True)),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('KEEP', 'Keep'), ('DONATE', 'Donate'), ('SELL', 'Sell'), ('DISCARD', 'Discard')], default='KEEP', max_length=10)),
                ('condition_flags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('donation_dest', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='triage.book')),
            ],
        ),
    ]
