# Generated by Django 6.0.3 on 2026-04-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='catalogentry',
            name='condition_grade',
            field=models.CharField(choices=[('MINT', 'Mint'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=10),
        ),
        migrations.AddField(
            model_name='catalogentry',
            name='valuation_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
