# Generated by Django 6.0.3 on 2026-04-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_cullinggoal_catalogentry_ai_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogentry',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
