# Generated by Django 6.0.3 on 2026-04-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0004_catalogentry_resolved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='catalogentry',
            name='resolved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogentry',
            name='status',
            field=models.CharField(choices=[('KEEP', 'Keep'), ('DONATE', 'Donate'), ('SELL', 'Sell'), ('DISCARD', 'Discard')], db_index=True, default='KEEP', max_length=10),
        ),
    ]
