# Generated by Django 6.0.3 on 2026-04-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0006_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
