# Generated by Django 6.0.3 on 2026-04-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0007_book_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogentry',
            name='marketplace_description',
            field=models.TextField(blank=True),
        ),
    ]
