# Generated by Django 6.0.3 on 2026-04-08 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0008_catalogentry_marketplace_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cullinggoal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='culling_goals', to=settings.AUTH_USER_MODEL),
        ),
    ]
