# Generated by Django 6.0.3 on 2026-04-08 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_users(apps, schema_editor):
    """
    Backfills a default user for existing records to support multi-tenancy.

    This function ensures that any CatalogEntry or CullingGoal records created
    before the 'user' field was mandatory are associated with the first
    available user (typically the primary admin).

    If no users exist in the system, it returns gracefully without performing
    any updates, allowing fresh installations to proceed.
    """
    User = apps.get_model(settings.AUTH_USER_MODEL)
    CullingGoal = apps.get_model("triage", "CullingGoal")
    CatalogEntry = apps.get_model("triage", "CatalogEntry")

    # Use the first available user (likely the admin from setup) as the owner
    # for any orphaned records created during the multi-tenant migration.
    first_user = User.objects.order_by("id").first()

    if not first_user:
        # If no users exist yet, we cannot perform a backfill.
        # This is expected in fresh environments or initial test runs.
        return

    # Update orphaned records to point to the first user.
    CullingGoal.objects.filter(user__isnull=True).update(user=first_user)
    CatalogEntry.objects.filter(user__isnull=True).update(user=first_user)


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0009_add_user_to_cullinggoal_and_catalogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(backfill_users, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='catalogentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cullinggoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culling_goals', to=settings.AUTH_USER_MODEL),
        ),
    ]
